it-pu/puis

.gitignore, Catatan.txt, application/config/routes.php, application/controllers/api/C_global.php, application/controllers/page/finance/C_finance.php, application/controllers/page/vreservation/C_global.php, application/controllers/page/vreservation/C_transaksi.php, application/models/master/M_master.php, application/models/vreservation/M_reservation.php, application/views/page/vreservation/menu_navigation.php, application/views/page/vreservation/modal_form.php, application/views/page/vreservation/schedule.php, application/views/page/vreservation/transaksi/booking.php
=> update vreservation modal

application/controllers/page/admission/C_admission.php, application/models/admission/M_admission.php, application/models/vreservation/M_reservation.php, application/views/page/admission/distribusi_formulir/LoadListPenjualanoffline.php
update vreservation integration exam
=> update adm offline list per division

application/config/routes.php, application/controllers/api/C_api.php, application/views/page/academic/tahunakademik/detail_tahun_akademik.php, application/views/page/academic/tahunakademik/tahun_akademik.php, application/views/template/include.php
=> special case KRS

application/config/routes.php, application/controllers/api/C_rest.php, application/models/M_rest.php
=> rest transcript

application/controllers/api/C_api.php, application/controllers/api/C_rest.php
=> Counseling

application/controllers/C_login.php, application/controllers/api/C_api.php, application/views/page/academic/timetables/edit_course.php, application/views/page/academic/timetables/setting_timetable.php
=> timetables

application/config/config.php
=> update config - permitted_uri_chars

application/config/routes.php, application/controllers/page/hr/C_employees.php, application/views/page/human-resources/employees/employees_files.php
=> delete file - dokumen lecturer HR

application/config/routes.php, application/controllers/auth/C_auth.php
=> Get Report Edom - Per Angkatan

application/controllers/api/C_api.php, application/models/M_api.php, application/views/page/academic/tahunakademik/detail_tahun_akademik.php, application/views/template/header.php
=> Create Setting Attendance - Diseting setiap semester di Academic Year

application/controllers/api/C_api.php, application/models/M_api.php
=> Service KRS Online

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/page/academic/C_study_planning.php, application/views/page/academic/studyplanning/course_offer.php
=> Bug Fix - Study Planning

application/controllers/api/C_api.php, application/views/page/academic/transfer_student/transfer_prodi.php
=> Pemindahan Data Payment saat Transfer Student

application/controllers/api/C_rest.php
=> Bug Fix discussion board

application/controllers/api/C_api.php, application/views/page/academic/transfer_student/transfer_prodi.php
=> Transfer student - Financial Student

application/controllers/api/C_api.php, application/views/page/academic/transfer_student/transfer_prodi.php
=> API Approve All KRS Online By Kaprodi

application/views/page/academic/transfer_student/course_conversion.php, application/views/page/academic/transfer_student/transfer_prodi.php
=> Push Toastr - Transfer Student

application/controllers/api/C_api.php, application/views/page/academic/studyplanning/course_offer.php
=> Bug Fix Study Plan - Academic

application/controllers/api/C_api.php
=> Insert Credit In Study Planning

application/controllers/api/C_api.php, application/controllers/auth/C_auth.php, application/views/page/academic/studyplanning/course_offer.php, application/views/page/academic/transfer_student/course_conversion.php, application/views/page/academic/transfer_student/transfer_prodi.php
=> Bug Fixing - Transfer Student

application/controllers/api/C_api.php, application/views/page/academic/studyplanning/batal_tambah.php
=> Fix bug batal tambah krs

application/views/page/academic/studyplanning/batal_tambah.php
=> Bug Fix Batal Tambah KRS

application/config/routes.php, application/controllers/C_save_to_pdf.php, application/controllers/api/C_api.php, application/models/report/M_save_to_pdf.php, application/views/page/academic/transcript/transcript_list_student.php
Signed-off-by: Agustian <agustian@podomorouniversity.ac.id>
=> report skl

application/config/routes.php, application/controllers/api/C_api2.php, application/controllers/api/C_global.php, application/views/global/academic/schedule-exchange/ex_approve.php, application/views/global/academic/schedule-exchange/ex_rejected.php, application/views/template/include.php, application/views/template/template_blank.php
=> Schedule Exchange - Lecturer

application/controllers/api/C_api2.php
=> Send email - Exchange Schedule

application/controllers/C_save_to_pdf.php
Signed-off-by: Agustian <agustian@podomorouniversity.ac.id>
=> revisiReportSKL

application/controllers/api/C_api2.php, application/controllers/page/ga/C_schedule_exchange.php
=> Approve All Modify Attendance - Kaprodi

application/models/M_rest.php
=> Fixing Transcript - Transfer Student

application/views/page/academic/tahunakademik/detail_tahun_akademik.php
=> Label - attd out

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/controllers/page/academic/C_presensi.php, application/views/page/academic/presensi/details_attendace.php, application/views/page/academic/presensi/menu_presensi.php, application/views/page/academic/presensi/monitoring_attendance.php, application/views/page/academic/tahunakademik/detail_tahun_akademik.php, application/views/template/include.php, assets/datatables/dataTables.rowsGroup.js
=> Monitoring Attendance

application/views/page/academic/presensi/monitoring_schedule_exchange.php
=> Hide status number Schedule Exchange

application/views/page/human-resources/monitoring/tab_monitoring.php
=> Modul HR - Remove label (Under Testing)

application/controllers/api/C_api.php, application/models/M_api.php, application/views/page/academic/presensi/monitoring_lecturer.php, application/views/page/academic/timetables/list_timetables.php
=> Bug Fix Show student - timetables

application/models/report/M_save_to_pdf.php
=> Showing Schedule Exchange - Manual Attendance

application/controllers/api/C_api2.php, application/views/page/academic/presensi/details_attendace.php
=> Change time - Schedule Exchange

application/controllers/api/C_api2.php, application/views/page/academic/presensi/details_attendace.php
=> Clean Attendance

application/models/report/M_save_to_pdf.php
=> Bug Fixing - Attendance Manual

application/controllers/api/C_api2.php, application/models/M_api.php, application/views/page/academic/presensi/details_attendace.php
=> Modify Schedule Exchange

application/controllers/api/C_api2.php, application/views/page/academic/presensi/details_attendace.php
- Schange Status -> set room GA if edit scheduke exchange
=> - Show Class Room in Attendance

application/views/page/academic/presensi/monitoring_attendance.php
=> Placeholder data tables - List Attendance

application/controllers/api/C_api.php, application/controllers/auth/C_auth.php, application/models/M_api.php, application/views/page/academic/timetables/list_timetables.php
=> timetables - Module Add & Dell Attendance

application/controllers/api/C_api2.php, application/controllers/auth/C_auth.php, application/models/M_rest.php, application/views/template/pengawas_ujian.php
=> Attendance for Exam

application/models/report/M_save_to_pdf.php
=> Show / Hide Transcript

application/config/routes.php, application/controllers/C_save_to_pdf.php, application/controllers/api/C_api.php, application/controllers/page/academic/C_jadwal_ujian.php, application/models/M_api.php, application/models/report/M_save_to_pdf.php, application/views/page/academic/jadwalujian/exam_setting.php, application/views/page/academic/jadwalujian/list_exam.php, application/views/page/academic/jadwalujian/menu_jadwal_ujian.php, application/views/page/academic/jadwalujian/set_exam_schedule.php, application/views/page/academic/presensi/details_attendace.php, application/views/page/academic/timetables/menu_timetables.php, application/views/template/include.php, application/views/template/pengawas_ujian.php
- Update halaman pengawas (attendance online)
- Show Review BAP
- Set schedule for make-up exams
=> - Bug Fixing KRS Online

application/controllers/C_save_to_pdf.php
Signed-off-by: Agustian <agustian@podomorouniversity.ac.id>
=> Revisi_SKL

application/controllers/C_save_to_pdf.php
Signed-off-by: Agustian <agustian@podomorouniversity.ac.id>
=> Revisi_odd

application/controllers/api/C_api.php, application/views/page/academic/jadwalujian/exam_setting.php, application/views/page/academic/jadwalujian/list_exam.php
=> exam setting

application/config/routes.php, application/controllers/api/C_rest.php, application/controllers/auth/C_auth.php, application/models/M_rest.php, application/views/page/academic/jadwalujian/exam_setting.php
=> Exam Schedule

application/controllers/api/C_api.php
Signed-off-by: Bismar Gazali <bismar.gazali@podomorouniversity.ac.id>
=> Bug Fixing

application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/models/M_api.php, application/models/M_rest.php, application/models/report/M_save_to_pdf.php, application/views/page/academic/jadwalujian/exam_setting.php, application/views/page/academic/jadwalujian/set_exam_schedule.php, application/views/template/pengawas_ujian.php
=> List Attendance Student

application/controllers/api/C_api2.php
=> bug fixing attendance pengawas

application/views/global/help/help.php
=> Help Style

application/views/global/help/help.php
=> View Help ID

application/controllers/api/C_rest.php, application/models/M_rest.php
=> Lecturer Exam Schedule

application/models/M_rest.php
=> Api class pengganti

application/controllers/api/C_api.php, application/models/M_api.php
=> Bug Fix Monitoring Attendnace Student

application/controllers/api/C_api2.php, application/models/M_api.php, application/views/page/academic/tahunakademik/detail_tahun_akademik.php
=> Setting Modify Attendance

application/views/page/it/ruleservice/page.php, application/views/template/header.php
=> test notive

application/views/page/academic/jadwalujian/edit_exam_schedule.php
=> Bug Fixing Edit Exam Scehdule

application/controllers/api/C_api2.php, application/controllers/page/announcement/C_announcement.php, application/views/page/academic/presensi/details_attendace.php
=> Need Clear All

application/controllers/api/C_api2.php
=> Show Need Clear

application/controllers/api/C_api.php
=> Hide Edit - Ujian Susulan

application/controllers/api/C_mobile.php
=> Mobile URL Photo

application/views/template/header.php, server.js
=> mobile_notif - Header

application/config/routes.php, application/controllers/api/C_api2.php, application/views/page/announcement/create_announcement.php, application/views/page/announcement/list_announcement.php
=> Announcement

application/views/page/announcement/create_announcement.php
=> show message

application/views/page/announcement/create_announcement.php
=> Hide Start Announcement

application/controllers/api/C_api2.php, application/views/page/announcement/create_announcement.php, application/views/page/announcement/edit_announcement.php
=> list announcement

application/views/page/announcement/create_announcement.php, application/views/page/announcement/edit_announcement.php
=> Change Label

application/views/page/announcement/create_announcement.php, application/views/page/announcement/edit_announcement.php
=> File sizing

application/views/page/announcement/create_announcement.php, application/views/page/announcement/edit_announcement.php
=> Alert maximum file upload

application/controllers/api/C_api.php, application/views/page/announcement/create_announcement.php, application/views/template/include.php
=> course name

application/controllers/api/C_api2.php, application/views/page/announcement/list_announcement.php
=> Show Unread, Read, Saved

application/controllers/api/C_mobile.php
=> Data Login Mobile

application/config/routes.php, application/controllers/api/C_mobile.php
=> Bug Fix Mobile Data

application/controllers/api/C_mobile.php
=> Bug Fixing Data Mobile

application/controllers/api/C_mobile.php, application/models/M_rest.php
=> Api Mobile

application/controllers/api/C_api2.php, application/controllers/api/C_mobile.php
=> Mobile Announcement

application/controllers/api/C_mobile.php
=> ordering announcement mobile

application/models/M_api.php
=> Bug Fix Menu Score

application/config/routes.php, application/controllers/api/C_api2.php, application/models/M_api.php
=> get semester for student

application/config/routes.php, application/controllers/api/C_api2.php
=> change password

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/models/M_api.php, application/views/template/header.php, application/views/template/pengawas_ujian.php
=> Button Attendance Pengawas

application/controllers/api/C_api2.php, application/views/page/announcement/edit_announcement.php, application/views/template/pengawas_ujian.php
- Countdown Auto Log Out Pengawas
=> - Remove Announcement

application/controllers/api/C_api2.php
=> result json

application/controllers/api/C_api2.php
=> Bug Fix Curriculum Mobile

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/models/M_api.php, application/models/M_rest.php, application/views/page/academic/jadwalujian/list_exam.php, application/views/page/academic/semesterantara/semester_antara.php
=> - Semester Antara

application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/views/page/database/students/editStudent.php
=> Edit Name Student

application/controllers/C_save_to_pdf.php
=> No surat mengajar

application/controllers/C_save_to_pdf.php
=> bug fixing surat mengajar

application/controllers/C_save_to_pdf.php
=> Revisi Surat Tugas Mengajar Bu Yasinta

application/controllers/C_save_to_pdf.php
=> Revisi 2 - Bu Yasinta

application/controllers/api/C_api.php, application/controllers/api/C_api2.php, application/models/M_rest.php, application/views/page/academic/semesterantara/sa_setting.php, application/views/page/academic/semesterantara/sa_setting_timetable.php
=> Semester Antara Setting

application/config/routes.php, application/controllers/api/C_api2.php, application/views/page/academic/presensi/details_attendace.php
=> exchange & venue

application/config/routes.php, application/controllers/api/C_api2.php, application/controllers/page/hr/C_employees.php
=> Upload Document Lecturer

application/controllers/api/C_api2.php, application/controllers/page/academic/C_kurikulum.php, application/views/page/academic/kurikulum/kurikulum_detail_cross.php, application/views/page/academic/semesterantara/sa_timetable.php
=> Semester Antara & Bug Fix Curriculum Cross

application/models/M_rest.php
=> Pengawas Semester Antara

application/config/routes.php, application/controllers/api/C_api2.php, application/models/M_rest.php
=> Edom Mobile

application/views/page/academic/kurikulum/kurikulum_detail_cross.php
=> Kros Kurikulum Status Biru

application/controllers/C_save_to_pdf.php, application/controllers/api/C_api2.php, application/models/report/M_save_to_pdf.php, application/views/page/academic/semesterantara/sa_timetable.php
=> Dokumen Exam Semester Antara

application/controllers/api/C_mobile.php, application/views/page/academic/semesterantara/menu_semester_antara.php
=> Bug Fix show schedule Mobile

application/controllers/api/C_api2.php, application/views/page/academic/semesterantara/sa_students.php
=> Bug Fixing Semester Antara

application/controllers/api/C_api2.php, application/models/M_rest.php
=> Update transcript semester antara

application/config/routes.php, application/controllers/api/C_api2.php, application/controllers/api/C_mobile.php, application/controllers/api/C_rest2.php, application/models/M_rest.php, application/views/page/academic/semesterantara/sa_setting_timetable.php, application/views/page/admission/crm/crmteam.php, application/views/page/admission/crm/prospective_students.php
=> Update CRM & Bug Fixing Update Transcript Semester Antara

application/views/page/academic/kurikulum/kurikulum.php, application/views/page/academic/kurikulum/kurikulum_detail.php
=> edit kurikulum

application/controllers/api/C_api.php, application/views/page/academic/semesterantara/semester_antara.php
=> Publish / Unpublish semester antara

application/views/page/academic/tahunakademik/detail_tahun_akademik.php
=> update edom 2 - sarana pra sarana

application/controllers/api/C_api2.php, application/controllers/api/C_rest2.php
=> CRM Mobile

application/controllers/api/C_mobile.php, application/controllers/api/C_rest2.php
=> Mobile CRM

application/controllers/api/C_rest2.php
=> view All contact

application/controllers/api/C_rest2.php
=> search contact

application/controllers/api/C_rest2.php
=> view kontak CRM

application/controllers/api/C_rest2.php, application/views/page/admission/crm/prospective_students.php
=> crm prospect student

application/views/page/admission/distribusi_formulir/LoadInputPenjualanoffline2.php
=> Status Email

application/views/page/admission/crm/prospective_students.php, application/views/template/include.php
=> hide option status

application/controllers/api/C_api2.php, application/controllers/api/C_api3.php, application/controllers/page/admission/C_admission.php, application/views/page/agregator/setting.php, application/views/template/header.php
=> bug fixing crm web

application/controllers/api/C_api2.php
=> bug fixing crm team

application/controllers/page/admission/marketing/C_crm.php
=> bug fixing search CRM

application/config/routes.php, application/controllers/api/C_api3.php, application/controllers/page/agregator/C_agregator.php, application/views/page/agregator/audit_keuangan_eksternal.php, application/views/page/agregator/kerjasama_perguruan_tinggi.php
=> kerjasama perguruan tinggi

application/controllers/api/C_rest2.php
=> bug fixing CRM Mobile

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/controllers/page/agregator/C_agregator.php, application/controllers/page/hr/C_employees.php, application/views/page/agregator/jabatan_dosen_tetap.php, application/views/page/agregator/kecukupan_dosen.php, application/views/page/agregator/mahasiswa_asing.php, application/views/page/agregator/seleksi_mahasiswa_baru.php, application/views/page/agregator/sertifikasi_dosen.php, application/views/page/human-resources/employees/editEmployees.php, application/views/template/include.php
=> Certificaed

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/controllers/page/it/C_it.php, application/views/page/academic/kurikulum/kurikulum.php, application/views/page/it/academic/redundancy_krs_online.php, application/views/page/it/menu_navigation.php, application/views/page/it/ruleservice/page.php, application/views/template/header.php, application/views/template/include.php
=> page - cleaning krs data

application/views/page/it/academic/redundancy_krs_online.php
=> hide input

application/controllers/api/C_api3.php
=> Bug fixing Monitoring Yudisium

application/controllers/api/C_api.php, application/views/page/database/students/editStudent.php
=> show Acc4ess Card

application/controllers/api/C_api.php
=> bug fixing krs online

application/config/routes.php, application/controllers/api/C_api3.php, application/views/page/academic/studyplanning/liststudent.php
=> Change Default Credit

application/controllers/C_login.php
=> Login from lecturer

application/config/routes.php, application/controllers/api/C_mobile.php
=> get SemesterActive versi mobile

application/views/template/header.php
=> login employees in lecturer

application/controllers/api/C_api.php
=> batal tambah to std_study_planning

application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/models/M_api.php, application/views/page/human-resources/monitoring/with_range_date.php, application/views/page/library/yudisium/final_project.php
=> report HRD

application/config/database.php, application/views/page/human-resources/monitoring/with_range_date.php
=> default lecturer

application/views/page/agregator_aps/kerjasama_tridharma.php
=> View Prodi

application/config/database.php
=> database config

application/config/routes.php, application/controllers/C_save_to_excel2.php, application/views/page/agregator_aps/programme_study.php
=> APS - Program Study

application/views/page/agregator/jabatan_dosen_tetap.php, application/views/page/agregator/kecukupan_dosen.php, application/views/template/include.php, assets/jquerytable2excel/jquery.table2excel.js
=> Jquery table 2 excel

application/views/page/agregator/kecukupan_dosen.php
=> css kecukupan dosen

application/views/page/agregator/prestasi_akademik_mahasiswa.php, application/views/page/agregator/prestasi_non_akademik_mahasiswa.php, application/views/page/student-life/menu_navigation.php
=> 3a1 & 3a2 APT

application/views/page/human-resources/employees/editEmployees.php, application/views/page/human-resources/employees/inputEmployees.php
=> Status Forlap

application/controllers/api/C_api3.php, application/views/page/agregator/audit_keuangan_eksternal.php, application/views/page/agregator/kerjasama_perguruan_tinggi.php, application/views/page/agregator/menu_agregator.php, application/views/page/agregator/perolehan_dana.php, application/views/page/agregator/perolehan_dana2.php
=> Agregator 4a

application/views/page/agregator/perolehan_dana.php
=> 4a Provilage

application/views/page/agregator/perolehan_dana.php
=> form edit keuangan 4

application/views/page/agregator/sertifikasi_dosen.php
=> bug fixing serdos

application/controllers/api/C_api3.php, application/views/page/agregator/dosen_tidak_tetap.php, application/views/page/agregator/jabatan_dosen_tetap.php, application/views/page/agregator/kecukupan_dosen.php, application/views/page/agregator/sertifikasi_dosen.php, application/views/template/header.php
=> show detail dosen agregator table 3

application/views/page/agregator/rasio_dosen_mahasiswa.php
=> rasio dosen on progress

application/views/page/agregator/jabatan_dosen_tetap.php, application/views/page/agregator/sertifikasi_dosen.php
=> Bug fixing 3

application/views/page/agregator/dosen_tidak_tetap.php
=> Bug fixing jumlah - dosen tidak tetap

application/controllers/api/C_api3.php, application/views/page/agregator/rasio_dosen_mahasiswa.php
=> rasio-dosen-mahasiswa

application/controllers/api/C_api3.php, application/views/page/agregator/rasio_dosen_mahasiswa.php
=> Status Student

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/controllers/page/student-life/C_studentlife.php, application/views/page/agregator/prestasi_akademik_mahasiswa.php, application/views/page/agregator/prestasi_non_akademik_mahasiswa.php, application/views/page/student-life/menu_navigation.php, application/views/page/student-life/student-achievement/menu_student_achievement.php, application/views/page/student-life/student-achievement/student_achievement.php, application/views/page/student-life/student-achievement/update_data_achievement.php
=> Student Life

application/controllers/api/C_api3.php
=> log employees

application/controllers/api/C_api3.php, application/views/page/it/user-activity/user_activity.php
=> Bug fixing user act

application/controllers/api/C_api3.php, application/views/page/it/user-activity/user_activity.php
=> user Activities

application/controllers/api/C_api3.php, application/views/page/it/user-activity/user_activity.php
=> activity fix view url

application/config/routes.php, application/controllers/api/C_api3.php, application/controllers/dashboard/C_dashboard.php, application/views/dashboard/myactivities.php, application/views/template/header.php
=> My activities

application/controllers/C_save_to_pdf.php, application/models/report/M_save_to_pdf.php
=> Bug Ijazah & Transkrip

application/config/routes.php, application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/controllers/page/student-life/C_studentlife.php, application/models/M_rest.php, application/views/page/student-life/tracer-alumni/form_accreditation.php, application/views/page/student-life/tracer-alumni/menu_stracer_alumni.php
- Form Akreditasi untuk alumni
=> - bug fixing transfer studi

application/config/routes.php, application/controllers/api/C_api3.php, application/views/page/student-life/tracer-alumni/form_accreditation.php, application/views/page/student-life/tracer-alumni/list_alumni.php
=> tracer alumni & open tugas akhir

application/views/dashboard/profile.php
=> hide profe

application/views/page/it/agregator/agregator_menu.php
=> summer note description

application/controllers/api/C_api3.php, application/views/page/agregator/waktu_tunggu_lulusan.php
=> waktu tunggu lulus

application/views/page/agregator/rasio_dosen_mahasiswa.php
=> Rasio dosen : mhs

application/config/routes.php, application/controllers/page/agregator/C_agregator.php, application/views/page/agregator/kepuasan_pengguna_lulusan.php, application/views/page/agregator/penggunaan_dana.php
=> agregator tempat_kerja_lulusan

application/views/page/database/students.php
=> show btn login portal std

application/controllers/api/C_api.php, application/views/page/database/employees.php, application/views/template/header.php
=> Reset password DDMMYY

application/controllers/api/C_api3.php, application/views/page/agregator/kesesuaian_bidang_kerja_lulusan.php, application/views/page/agregator/waktu_tunggu_lulusan.php
=> waktu tunggu lulus & Kesesuaian kerjaan

application/views/page/agregator/kesesuaian_bidang_kerja_lulusan.php
=> change year

application/controllers/api/C_api.php
Signed-off-by: alhadi rahman <alhadi.rahman@podomorouniversity.ac.id>
=> time format request document

application/config/routes.php, application/controllers/api/C_api3.php, application/views/page/student-life/menu_navigation.php, application/views/page/student-life/tracer-alumni/list_alumni.php, application/views/page/student-life/tracer-alumni/menu_stracer_alumni.php
=> StudentLife

application/controllers/api/C_api3.php, application/controllers/page/agregator/C_agregator.php, application/views/page/agregator/kepuasan_pengguna_lulusan.php, application/views/page/agregator/kesesuaian_bidang_kerja_lulusan.php, application/views/page/agregator/table_refrensi.php, application/views/page/agregator/tempat_kerja_lulusan.php, application/views/page/agregator/waktu_tunggu_lulusan.php, application/views/page/student-life/tracer-alumni/list_alumni.php, application/views/template/include.php
=> Kesesuaian bidang kerja

application/controllers/api/C_api3.php
=> Banyaknya lulusan yang bekerja

application/config/routes.php, application/views/page/academic/studyplanning/menu_studyplan.php
=> study planning

application/controllers/api/C_api.php
=> Bug fix edom quetion

application/views/page/academic/score/inputScore.php, application/views/page/academic/score/score.php
=> bug fixing input score

application/controllers/api/C_api3.php, application/views/page/agregator/kepuasan_pengguna_lulusan.php, application/views/page/agregator/kepuasan_pengguna_lulusan2.php, application/views/page/agregator/table_refrensi.php, application/views/page/student-life/tracer-alumni/form_accreditation.php
=> Pengguna Lulusan

application/views/page/agregator/kepuasan_pengguna_lulusan.php
=> style detail 5e1

application/controllers/auth/C_auth.php, application/views/page/agregator/kepuasan_pengguna_lulusan.php, application/views/page/agregator/kesesuaian_bidang_kerja_lulusan.php, application/views/page/agregator/table_refrensi.php, application/views/page/agregator/tempat_kerja_lulusan.php, application/views/page/agregator/waktu_tunggu_lulusan.php
=> save 2 pdf

application/controllers/api/C_api3.php, application/views/page/agregator/jasa_yang_diadopsi.php
=> Prodi Jasa Yang di Adopsi

application/controllers/api/C_api3.php, application/controllers/page/hr/C_employees.php, application/views/page/student-life/student-achievement/update_data_achievement.php, application/views/template/include.php
=> upload file certificate in student life

application/controllers/api/C_api3.php, application/controllers/page/agregator/C_agregator.php, application/views/page/agregator/lama_studi_mahasiswa.php, application/views/page/agregator/sertifikat_kompetensi.php, application/views/page/student-life/student-achievement/update_data_achievement.php
=> student achievement

application/controllers/C_save_to_pdf.php
=> Transcript temp

application/controllers/C_save_to_pdf.php, application/controllers/api/C_api3.php, application/controllers/page/academic/C_final_project.php, application/models/M_rest.php, application/views/page/academic/finalproject/list_student.php, application/views/page/finance/yudisium/monitoring_yudisium.php, application/views/page/library/yudisium/monitoring_yudisium.php, application/views/template/header.php
=> bug fixing monitoring

application/controllers/C_save_to_pdf.php
=> Judicium_Clearance_Form

application/views/global/kb/kb.php
Signed-off-by: Novita Riani <novita.riani@podomorouniversity.ac.id>
=> update filesize upload

application/controllers/api/C_api3.php
=> fixing library

application/controllers/api/C_api3.php
=> bug fixing load

application/controllers/api/C_api3.php
=> member id library

application/controllers/C_save_to_pdf.php
=> remove qlib

application/controllers/C_save_to_pdf.php, application/controllers/api/C_api.php, application/views/template/include.php, index.php
=> SKPI bug fixing

application/controllers/C_save_to_pdf.php
=> SUPPLEMENT fixing

application/controllers/C_save_to_pdf.php
=> download skpi

application/controllers/C_save_to_pdf.php, application/controllers/api/C_api.php
=> Student tracking

application/controllers/page/academic/C_transfer_student.php
=> fixing popover note

application/controllers/api/C_api3.php, application/controllers/api/C_rest.php, application/controllers/page/academic/C_tahun_akademik.php, application/views/page/academic/finalproject/list_student.php, application/views/page/academic/finalproject/monitoring_yudisium.php, application/views/page/academic/tahunakademik/tahun_akademik.php, application/views/template/include.php
=> final project

application/controllers/api/C_api3.php, application/models/M_api.php, application/views/page/academic/finalproject/monitoring_yudisium.php
=> monitoring judiciums

application/controllers/api/C_api.php, application/controllers/api/C_api3.php, application/controllers/api/C_upload.php, application/views/page/academic/finalproject/monitoring_yudisium.php, application/views/template/include.php
=> bug fixing library final project

application/controllers/api/C_api3.php
change style button approval kaprodi
=> - Final Project

application/controllers/api/C_api3.php, application/views/page/academic/dashboard.php, application/views/page/student-life/medical-record/student_medical_record.php, application/views/template/pengawas_ujian.php
=> bug fixing academic

application/views/page/it/dashboard.php
=> dashboard IT

application/controllers/api/C_api3.php, application/controllers/page/student-life/C_medical_record.php, application/views/page/student-life/medical-record/medical_history.php, application/views/page/student-life/medical-record/menu_student_medical_record.php, application/views/page/student-life/medical-record/student_medical_record.php
- medical record
- medical history
=> Student medical record

application/config/routes.php
=> routes menu web prodi

application/controllers/api/C_rest3.php, application/views/page/academic/tahunakademik/tahun_akademik.php, application/views/template/header.php
Signed-off-by: Irfan Firdaus <irfan.firdaus@podomorouniversity.ac.id>
=> Calendar Academic

application/controllers/auth/C_auth.php, application/controllers/page/hr/C_employees.php, application/views/dashboard/check_sks.php, application/views/page/human-resources/monitoring/lecturer_fees.php, application/views/page/human-resources/monitoring/tab_monitoring.php
Check sks
Signed-off-by: Nandang Mulyadi <nandang.mulyadi@podomorouniversity.ac.id>
=> Lecturer Fees & Check sks

application/controllers/api/C_rest.php
Signed-off-by: Nandang Mulyadi <nandang.mulyadi@podomorouniversity.ac.id>
=> Fixing forum

application/views/page/academic/studyplanning/liststudent.php
Signed-off-by: Nandang Mulyadi <nandang.mulyadi@podomorouniversity.ac.id>
=> fixing krs online

application/controllers/page/it/C_it.php, application/controllers/page/lpmi/C_lpmi.php, application/views/page/database/admisi/requestMerging.php, application/views/page/lpmi/edom/list_result.php
=> insurance-update-approval

application/controllers/page/global-informations/C_global_informations.php, application/controllers/page/hr/C_employees.php, application/views/dashboard/global-informations/message-blast/list.php, application/views/page/human-resources/employees/additional-information.php, application/views/page/human-resources/employees/attendance.php, application/views/page/human-resources/employees/career-level.php, application/views/page/human-resources/employees/editEmployees.php, application/views/page/human-resources/employees/education.php, application/views/page/human-resources/employees/experience.php, application/views/page/human-resources/employees/family.php, application/views/page/human-resources/employees/inputEmployees.php, application/views/page/human-resources/employees/tab_menu_new_emp.php, application/views/page/human-resources/menu_navigation.php
=> global-info-mail-blast-bug

application/controllers/page/hr/C_aphris.php, application/controllers/page/hr/C_employees.php, application/views/dashboard/global-informations/message-blast/filter/Employee.php, application/views/dashboard/global-informations/message-blast/filter/Lecturer.php, application/views/dashboard/global-informations/message-blast/filter/Student.php, application/views/dashboard/global-informations/message-blast/formParticipants.php, application/views/page/human-resources/aphris/index.php, application/views/page/human-resources/aphris/structure-organization/index.php, application/views/page/human-resources/employees/additional-information.php, application/views/page/human-resources/employees/tab_menu_new_emp.php, application/views/page/human-resources/menu_navigation.php
=> global-info-check-format-mail

application/controllers/api/C_api.php, application/controllers/page/hr/C_aphris.php, application/controllers/page/hr/C_employees.php, application/models/hr/M_hr.php, application/views/page/human-resources/aphris/index.php, application/views/page/human-resources/aphris/structure-organization/detail.php, application/views/page/human-resources/aphris/structure-organization/index.php, application/views/page/human-resources/employees/career-level.php, application/views/page/human-resources/employees/tab_menu_new_emp.php, application/views/page/human-resources/menu_navigation.php, assets/OrgChart/dist/js/jquery.orgchart.js
=> Febri aphris hr

assets/template/css/main.css
Signed-off-by: Nandang Mulyadi <nandang.mulyadi@podomorouniversity.ac.id>
=> font template

application/controllers/api/C_api.php, application/controllers/api/C_api4.php, application/controllers/page/academic/C_transcript.php, application/views/page/academic/presensi/monitoring_online_class.php, application/views/page/academic/transcript/ijazah.php, application/views/page/academic/transcript/transcript_list_student.php, application/views/template/include.php
- Reconfirm attendance student
- Genrate Ijazah
=> Reconfirm attendance student

application/views/template/header.php, firebase-messaging-sw.js
=> Icon Notification

application/controllers/C_save_to_pdf.php
Signed-off-by: Irfan Firdaus <irfan.firdaus@podomorouniversity.ac.id>
=> Change Mk Eng to Mk ind Surat mengajar

application/controllers/api/C_apilppm.php, application/controllers/page/lppm/C_lppm.php, application/controllers/page/student-life/C_studentlife.php, application/models/student-life/M_podivers.php, application/views/page/lppm/content/menu_content.php, application/views/page/lppm/menu_navigation.php, application/views/page/student-life/podivers/list_podivers.php
=> Update LPPM commite

application/controllers/api/C_api3.php, application/views/page/agregator/ipk.php, application/views/page/agregator/lama_studi_mahasiswa.php, application/views/page/agregator/produktivitas_penelitian_dosen.php, application/views/page/agregator/produktivitas_pkm_dosen.php, application/views/page/agregator/publikasi_ilmiah.php
3c1, 3c2 --> yes
5a1 -> yes
5c1 --> yes
5f --> yes
5.g.1 --> yes
start 2014
=> 1c --> yes (done)

application/controllers/page/share-menu/C_rps.php, application/models/it/rps/M_rps.php, application/views/page/share-menu/rps/action_modal.php, application/views/page/share-menu/rps/bahan_kajian.php, application/views/page/share-menu/rps/curriculum_detail.php, application/views/page/share-menu/rps/data_curriculum.php, application/views/page/share-menu/rps/desc_mk.php, application/views/page/share-menu/rps/list_cpmk.php, application/views/page/share-menu/rps/list_rps.php, application/views/page/share-menu/rps/manage_cpl.php, application/views/page/share-menu/rps/master_cpl.php, application/views/page/share-menu/rps/menu_rps.php
feat(Modul RPS): Menambahkan modul RPS
=> feat(Modul RPS): Menambahkan modul RPS
